builds:
  - id: pebble
    main: .
    binary: pbl
    flags:
      - "--trimpath"
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64

archives:
  - format: binary
    name_template: "{{.Binary}}-{{.Os}}-{{.Arch}}"

brews:
  - name: pebble
    homepage: https://github.com/leberjs/homebrew-tools
    repository:
      owner: leberjs
      name: homebrew-tools

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
